[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.fuzz]
runs = 512

[profile.default.invariant]
runs = 256
depth = 64
fail_on_revert = false

[profile.ci.fuzz]
runs = 2048

[profile.ci.invariant]
runs = 512
depth = 128
